---
version: "2"

run:
  timeout: 30s
  tests: false

linters:
  default: none
  enable:
    # core correctness
    - govet
    - staticcheck
    - errcheck
    - errorlint
    - err113

    # architecture & policy
    # - depguard
    - forbidigo

    # resource lifecycle
    - bodyclose
    - spancheck

    # logic & runtime safety
    - copyloopvar
    - forcetypeassert
    - nilnil
    - nilerr

    # code quality & maintainability
    - revive
    - gocritic
    - goconst

    # error correctness
    - errname

    # style & formatting
    - tagliatelle

  settings:
    forbidigo:
      forbid:
        - pattern: "^fmt\\.Print(ln|f)?$"
          msg: "use structured logger"
        - pattern: "^time\\.Sleep$"
          msg: "blocks goroutine; use context-aware waits"

    revive:
      rules:
        - name: package-comments
          disabled: true
    gocritic:
      disable-all: false
      enabled-checks:
        - hugeParam
        - rangeValCopy
      settings:
        hugeParam:
          sizeThreshold: 80
        rangeValCopy:
          sizeThreshold: 512
    goconst:
      min-len: 2
      min-occurrences: 3

    tagliatelle:
      case:
        rules:
          json: snake
          koanf: snake
